create table "public"."seasons" (
    "id" bigint generated by default as identity not null,
    "id_league" bigint not null,
    "year" bigint not null,
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "current" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."seasons" enable row level security;

alter table "public"."countries" alter column "code" drop not null;

alter table "public"."countries" alter column "flag" drop not null;

alter table "public"."countries" alter column "id_api" drop not null;

alter table "public"."countries" alter column "name" drop not null;

CREATE UNIQUE INDEX seasons_id_key ON public.seasons USING btree (id);

CREATE UNIQUE INDEX seasons_pkey ON public.seasons USING btree (id);

alter table "public"."seasons" add constraint "seasons_pkey" PRIMARY KEY using index "seasons_pkey";

alter table "public"."seasons" add constraint "seasons_id_key" UNIQUE using index "seasons_id_key";

alter table "public"."seasons" add constraint "seasons_id_league_fkey" FOREIGN KEY (id_league) REFERENCES leagues(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."seasons" validate constraint "seasons_id_league_fkey";

grant delete on table "public"."seasons" to "anon";

grant insert on table "public"."seasons" to "anon";

grant references on table "public"."seasons" to "anon";

grant select on table "public"."seasons" to "anon";

grant trigger on table "public"."seasons" to "anon";

grant truncate on table "public"."seasons" to "anon";

grant update on table "public"."seasons" to "anon";

grant delete on table "public"."seasons" to "authenticated";

grant insert on table "public"."seasons" to "authenticated";

grant references on table "public"."seasons" to "authenticated";

grant select on table "public"."seasons" to "authenticated";

grant trigger on table "public"."seasons" to "authenticated";

grant truncate on table "public"."seasons" to "authenticated";

grant update on table "public"."seasons" to "authenticated";

grant delete on table "public"."seasons" to "service_role";

grant insert on table "public"."seasons" to "service_role";

grant references on table "public"."seasons" to "service_role";

grant select on table "public"."seasons" to "service_role";

grant trigger on table "public"."seasons" to "service_role";

grant truncate on table "public"."seasons" to "service_role";

grant update on table "public"."seasons" to "service_role";


