create table "public"."fixture_player_statistics" (
    "id" bigint generated by default as identity not null,
    "id_player" bigint not null,
    "id_fixture" bigint not null,
    "minutes" bigint not null,
    "number" bigint not null,
    "position" text not null,
    "rating" text not null,
    "captain" boolean not null default false,
    "substitute" boolean not null default false,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."fixture_player_statistics" enable row level security;

CREATE UNIQUE INDEX fixture_player_statistics_pkey ON public.fixture_player_statistics USING btree (id);

alter table "public"."fixture_player_statistics" add constraint "fixture_player_statistics_pkey" PRIMARY KEY using index "fixture_player_statistics_pkey";

alter table "public"."fixture_player_statistics" add constraint "fixture_player_statistics_id_fixture_fkey" FOREIGN KEY (id_fixture) REFERENCES fixtures(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fixture_player_statistics" validate constraint "fixture_player_statistics_id_fixture_fkey";

alter table "public"."fixture_player_statistics" add constraint "fixture_player_statistics_id_player_fkey" FOREIGN KEY (id_player) REFERENCES players(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fixture_player_statistics" validate constraint "fixture_player_statistics_id_player_fkey";

grant delete on table "public"."fixture_player_statistics" to "anon";

grant insert on table "public"."fixture_player_statistics" to "anon";

grant references on table "public"."fixture_player_statistics" to "anon";

grant select on table "public"."fixture_player_statistics" to "anon";

grant trigger on table "public"."fixture_player_statistics" to "anon";

grant truncate on table "public"."fixture_player_statistics" to "anon";

grant update on table "public"."fixture_player_statistics" to "anon";

grant delete on table "public"."fixture_player_statistics" to "authenticated";

grant insert on table "public"."fixture_player_statistics" to "authenticated";

grant references on table "public"."fixture_player_statistics" to "authenticated";

grant select on table "public"."fixture_player_statistics" to "authenticated";

grant trigger on table "public"."fixture_player_statistics" to "authenticated";

grant truncate on table "public"."fixture_player_statistics" to "authenticated";

grant update on table "public"."fixture_player_statistics" to "authenticated";

grant delete on table "public"."fixture_player_statistics" to "service_role";

grant insert on table "public"."fixture_player_statistics" to "service_role";

grant references on table "public"."fixture_player_statistics" to "service_role";

grant select on table "public"."fixture_player_statistics" to "service_role";

grant trigger on table "public"."fixture_player_statistics" to "service_role";

grant truncate on table "public"."fixture_player_statistics" to "service_role";

grant update on table "public"."fixture_player_statistics" to "service_role";


