create table "public"."fixtures" (
    "id" bigint generated by default as identity not null,
    "id_api" bigint not null,
    "id_round" bigint not null,
    "id_home" bigint not null,
    "id_away" bigint not null,
    "date" timestamp with time zone not null,
    "score" json not null,
    "goals" json not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."fixtures" enable row level security;

CREATE UNIQUE INDEX fixtures_pkey ON public.fixtures USING btree (id);

alter table "public"."fixtures" add constraint "fixtures_pkey" PRIMARY KEY using index "fixtures_pkey";

alter table "public"."fixtures" add constraint "fixtures_id_away_fkey" FOREIGN KEY (id_away) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fixtures" validate constraint "fixtures_id_away_fkey";

alter table "public"."fixtures" add constraint "fixtures_id_home_fkey" FOREIGN KEY (id_home) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fixtures" validate constraint "fixtures_id_home_fkey";

alter table "public"."fixtures" add constraint "fixtures_id_round_fkey" FOREIGN KEY (id_round) REFERENCES rounds(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."fixtures" validate constraint "fixtures_id_round_fkey";

grant delete on table "public"."fixtures" to "anon";

grant insert on table "public"."fixtures" to "anon";

grant references on table "public"."fixtures" to "anon";

grant select on table "public"."fixtures" to "anon";

grant trigger on table "public"."fixtures" to "anon";

grant truncate on table "public"."fixtures" to "anon";

grant update on table "public"."fixtures" to "anon";

grant delete on table "public"."fixtures" to "authenticated";

grant insert on table "public"."fixtures" to "authenticated";

grant references on table "public"."fixtures" to "authenticated";

grant select on table "public"."fixtures" to "authenticated";

grant trigger on table "public"."fixtures" to "authenticated";

grant truncate on table "public"."fixtures" to "authenticated";

grant update on table "public"."fixtures" to "authenticated";

grant delete on table "public"."fixtures" to "service_role";

grant insert on table "public"."fixtures" to "service_role";

grant references on table "public"."fixtures" to "service_role";

grant select on table "public"."fixtures" to "service_role";

grant trigger on table "public"."fixtures" to "service_role";

grant truncate on table "public"."fixtures" to "service_role";

grant update on table "public"."fixtures" to "service_role";


