create table "public"."squads" (
    "id" bigint generated by default as identity not null,
    "id_season" bigint not null,
    "id_team" bigint not null,
    "id_player" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."squads" enable row level security;

CREATE UNIQUE INDEX squads_pkey ON public.squads USING btree (id);

alter table "public"."squads" add constraint "squads_pkey" PRIMARY KEY using index "squads_pkey";

alter table "public"."squads" add constraint "squads_id_player_fkey" FOREIGN KEY (id_player) REFERENCES players(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."squads" validate constraint "squads_id_player_fkey";

alter table "public"."squads" add constraint "squads_id_season_fkey" FOREIGN KEY (id_season) REFERENCES seasons(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."squads" validate constraint "squads_id_season_fkey";

alter table "public"."squads" add constraint "squads_id_team_fkey" FOREIGN KEY (id_team) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."squads" validate constraint "squads_id_team_fkey";

grant delete on table "public"."squads" to "anon";

grant insert on table "public"."squads" to "anon";

grant references on table "public"."squads" to "anon";

grant select on table "public"."squads" to "anon";

grant trigger on table "public"."squads" to "anon";

grant truncate on table "public"."squads" to "anon";

grant update on table "public"."squads" to "anon";

grant delete on table "public"."squads" to "authenticated";

grant insert on table "public"."squads" to "authenticated";

grant references on table "public"."squads" to "authenticated";

grant select on table "public"."squads" to "authenticated";

grant trigger on table "public"."squads" to "authenticated";

grant truncate on table "public"."squads" to "authenticated";

grant update on table "public"."squads" to "authenticated";

grant delete on table "public"."squads" to "service_role";

grant insert on table "public"."squads" to "service_role";

grant references on table "public"."squads" to "service_role";

grant select on table "public"."squads" to "service_role";

grant trigger on table "public"."squads" to "service_role";

grant truncate on table "public"."squads" to "service_role";

grant update on table "public"."squads" to "service_role";


