create table "public"."leagues" (
    "id" bigint generated by default as identity not null,
    "id_api" bigint not null,
    "id_country" bigint not null,
    "name" text not null,
    "logo" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."leagues" enable row level security;

CREATE UNIQUE INDEX leagues_id_key ON public.leagues USING btree (id);

CREATE UNIQUE INDEX leagues_pkey ON public.leagues USING btree (id);

alter table "public"."leagues" add constraint "leagues_pkey" PRIMARY KEY using index "leagues_pkey";

alter table "public"."leagues" add constraint "leagues_id_country_fkey" FOREIGN KEY (id_country) REFERENCES countries(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."leagues" validate constraint "leagues_id_country_fkey";

alter table "public"."leagues" add constraint "leagues_id_key" UNIQUE using index "leagues_id_key";

grant delete on table "public"."leagues" to "anon";

grant insert on table "public"."leagues" to "anon";

grant references on table "public"."leagues" to "anon";

grant select on table "public"."leagues" to "anon";

grant trigger on table "public"."leagues" to "anon";

grant truncate on table "public"."leagues" to "anon";

grant update on table "public"."leagues" to "anon";

grant delete on table "public"."leagues" to "authenticated";

grant insert on table "public"."leagues" to "authenticated";

grant references on table "public"."leagues" to "authenticated";

grant select on table "public"."leagues" to "authenticated";

grant trigger on table "public"."leagues" to "authenticated";

grant truncate on table "public"."leagues" to "authenticated";

grant update on table "public"."leagues" to "authenticated";

grant delete on table "public"."leagues" to "service_role";

grant insert on table "public"."leagues" to "service_role";

grant references on table "public"."leagues" to "service_role";

grant select on table "public"."leagues" to "service_role";

grant trigger on table "public"."leagues" to "service_role";

grant truncate on table "public"."leagues" to "service_role";

grant update on table "public"."leagues" to "service_role";


