create table "public"."teams" (
    "id" bigint generated by default as identity not null,
    "id_api" bigint not null,
    "id_country" bigint not null,
    "name" text not null,
    "logo" text not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."teams" enable row level security;

CREATE UNIQUE INDEX teams_id_api_key ON public.teams USING btree (id_api);

CREATE UNIQUE INDEX teams_pkey ON public.teams USING btree (id);

alter table "public"."teams" add constraint "teams_pkey" PRIMARY KEY using index "teams_pkey";

alter table "public"."teams" add constraint "teams_id_api_key" UNIQUE using index "teams_id_api_key";

alter table "public"."teams" add constraint "teams_id_country_fkey" FOREIGN KEY (id_country) REFERENCES countries(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."teams" validate constraint "teams_id_country_fkey";

grant delete on table "public"."teams" to "anon";

grant insert on table "public"."teams" to "anon";

grant references on table "public"."teams" to "anon";

grant select on table "public"."teams" to "anon";

grant trigger on table "public"."teams" to "anon";

grant truncate on table "public"."teams" to "anon";

grant update on table "public"."teams" to "anon";

grant delete on table "public"."teams" to "authenticated";

grant insert on table "public"."teams" to "authenticated";

grant references on table "public"."teams" to "authenticated";

grant select on table "public"."teams" to "authenticated";

grant trigger on table "public"."teams" to "authenticated";

grant truncate on table "public"."teams" to "authenticated";

grant update on table "public"."teams" to "authenticated";

grant delete on table "public"."teams" to "service_role";

grant insert on table "public"."teams" to "service_role";

grant references on table "public"."teams" to "service_role";

grant select on table "public"."teams" to "service_role";

grant trigger on table "public"."teams" to "service_role";

grant truncate on table "public"."teams" to "service_role";

grant update on table "public"."teams" to "service_role";


