create table "public"."league_season_teams" (
    "id" bigint generated by default as identity not null,
    "id_team" bigint not null,
    "id_league" bigint not null,
    "id_season" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."league_season_teams" enable row level security;

CREATE UNIQUE INDEX league_season_teams_pkey ON public.league_season_teams USING btree (id);

alter table "public"."league_season_teams" add constraint "league_season_teams_pkey" PRIMARY KEY using index "league_season_teams_pkey";

alter table "public"."league_season_teams" add constraint "league_season_teams_id_league_fkey" FOREIGN KEY (id_league) REFERENCES leagues(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_season_teams" validate constraint "league_season_teams_id_league_fkey";

alter table "public"."league_season_teams" add constraint "league_season_teams_id_season_fkey" FOREIGN KEY (id_season) REFERENCES seasons(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_season_teams" validate constraint "league_season_teams_id_season_fkey";

alter table "public"."league_season_teams" add constraint "league_season_teams_id_team_fkey" FOREIGN KEY (id_team) REFERENCES teams(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."league_season_teams" validate constraint "league_season_teams_id_team_fkey";

grant delete on table "public"."league_season_teams" to "anon";

grant insert on table "public"."league_season_teams" to "anon";

grant references on table "public"."league_season_teams" to "anon";

grant select on table "public"."league_season_teams" to "anon";

grant trigger on table "public"."league_season_teams" to "anon";

grant truncate on table "public"."league_season_teams" to "anon";

grant update on table "public"."league_season_teams" to "anon";

grant delete on table "public"."league_season_teams" to "authenticated";

grant insert on table "public"."league_season_teams" to "authenticated";

grant references on table "public"."league_season_teams" to "authenticated";

grant select on table "public"."league_season_teams" to "authenticated";

grant trigger on table "public"."league_season_teams" to "authenticated";

grant truncate on table "public"."league_season_teams" to "authenticated";

grant update on table "public"."league_season_teams" to "authenticated";

grant delete on table "public"."league_season_teams" to "service_role";

grant insert on table "public"."league_season_teams" to "service_role";

grant references on table "public"."league_season_teams" to "service_role";

grant select on table "public"."league_season_teams" to "service_role";

grant trigger on table "public"."league_season_teams" to "service_role";

grant truncate on table "public"."league_season_teams" to "service_role";

grant update on table "public"."league_season_teams" to "service_role";


